table fact_cutoffs

	/// The average Z-score cutoff for the selected context.
	measure 'Average Cutoff Z' = AVERAGE(fact_cutoffs[CutoffZ])

	/// The highest Z-score cutoff for the selected context.
	measure 'Max Cutoff Z' = MAX(fact_cutoffs[CutoffZ])

	/// The lowest Z-score cutoff for the selected context.
	measure 'Min Cutoff Z' = MIN(fact_cutoffs[CutoffZ])

	/// Count of courses where a valid Z-score was published.
	measure 'Available Cutoffs' =
			CALCULATE(
			    COUNTROWS(fact_cutoffs),
			    fact_cutoffs[CutoffStatus] = "AVAILABLE"
			)

	/// Distinct count of unique courses that had an available cutoff.
	measure 'Available Courses' =
			CALCULATE(
			    DISTINCTCOUNT(fact_cutoffs[CourseID]),
			    fact_cutoffs[CutoffStatus] = "AVAILABLE"
			)

	/// Count of courses marked as Not Qualified for Cutoff (NQC).
	measure 'NQC Count' =
			CALCULATE(
			    COUNTROWS(fact_cutoffs),
			    fact_cutoffs[CutoffStatus] = "NQC"
			)

	measure 'Cutoff Volatility' = STDEV.S(fact_cutoffs[CutoffZ])

	measure 'Volatility Level' = 
			VAR v = [Cutoff Volatility]
			RETURN IF(ISBLANK(v), BLANK(), IF(v <= 0.05, "Low", IF(v <= 0.15, "Medium", "High")))

	measure 'Competitiveness Index' = 
			VAR MeanZ = [Average Cutoff Z]
			VAR MinMeanZ = MINX(ALL(dim_course), CALCULATE([Average Cutoff Z]))
			VAR MaxMeanZ = MAXX(ALL(dim_course), CALCULATE([Average Cutoff Z]))
			VAR NormZ = DIVIDE(MeanZ - MinMeanZ, MaxMeanZ - MinMeanZ) * 100
			VAR Comp = NormZ - ([Cutoff Volatility] * 10)
			RETURN IF(ISBLANK(MeanZ), BLANK(), Comp)

	measure 'Competitiveness Band' = 
			VAR c = [Competitiveness Index]
			RETURN IF(ISBLANK(c), BLANK(), 
			    IF(c <= 20, "Lower historical cutoff", 
			        IF(c <= 40, "Moderate", 
			            IF(c <= 60, "Competitive", 
			                IF(c <= 80, "Highly competitive", "Extremely competitive")
			            )
			        )
			    )
			)

	measure 'YoY Cutoff Change' = 
			VAR CurrentYear = MAX(dim_year[ExamYear])
			VAR PrevYear = CurrentYear - 1
			VAR CurrentZ = [Average Cutoff Z]
			VAR PrevZ = CALCULATE([Average Cutoff Z], ALL(dim_year), dim_year[ExamYear] = PrevYear)
			RETURN IF(ISBLANK(CurrentZ) || ISBLANK(PrevZ), BLANK(), CurrentZ - PrevZ)

	column ExamYear
		dataType: int64
		isHidden
		sourceColumn: ExamYear

	column CourseID
		dataType: string
		isHidden
		sourceColumn: CourseID

	column UniversityID
		dataType: string
		isHidden
		sourceColumn: UniversityID

	column DistrictID
		dataType: string
		isHidden
		sourceColumn: DistrictID

	column CutoffZ
		dataType: double
		sourceColumn: CutoffZ

	column CutoffStatus
		dataType: string
		sourceColumn: CutoffStatus

	column AptitudeTest
		dataType: boolean
		sourceColumn: AptitudeTest

	column Page
		dataType: int64
		sourceColumn: Page

	column SourceFile
		dataType: string
		sourceColumn: SourceFile

	partition fact_cutoffs = m
		mode: import
		source =
			let 
			    Source = Parquet.Document(File.Contents("C:\Users\Dilhara Jayawardhana\Projects\Dev\DS-Projects\al-trends\data\bronze\parquet\fact_cutoffs.parquet")),
			    #"Removed Columns" = Table.RemoveColumns(Source, {"AcademicYear", "PublicationDate", "CourseName", "UniversityName", "DistrictName"})
			in 
			    #"Removed Columns"
