from __future__ import annotations

DISTRICTS = [
    "COLOMBO", "GAMPAHA", "KALUTARA", "MATALE", "KANDY",
    "NUWARA ELIYA", "GALLE", "MATARA", "HAMBANTOTA", "JAFFNA",
    "KILINOCHCHI", "MANNAR", "MULLAITIVU", "VAVUNIYA", "TRINCOMALEE",
    "BATTICALOA", "AMPARA", "PUTTALAM", "KURUNEGALA", "ANURADHAPURA",
    "POLONNARUWA", "BADULLA", "MONARAGALA", "KEGALLE", "RATNAPURA",
]

ACADEMIC_YEAR = "2025/2026"
EXAM_YEAR = 2025
PUBLICATION_DATE = "2026-07-31"
